version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
    gocyclo:
      min-complexity: 32
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
      - linters:
          - dupl
        path: pkg/sandbox-manager/api\.go
        text: "duplicate of"
    paths:
      - third_party$
      - builtin$
      - examples$
      - "_test\\.go$"
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
